CREATE TABLE "DATALAB"."CHURN_PREDICTIONS" 
   (    "CUSTOMERID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "GENDER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "TENURE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "MONTHLYCHARGES" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "TOTALCHARGES" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "SENTIMENTSCORE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "PREDICTION" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
