-- USER SQL
CREATE USER DATALAB IDENTIFIED BY Oracle1234##;

-- ADD ROLES
GRANT CONNECT TO DATALAB;
GRANT CONSOLE_DEVELOPER TO DATALAB;
GRANT DWROLE TO DATALAB;
GRANT GRAPH_DEVELOPER TO DATALAB;
GRANT OML_DEVELOPER TO DATALAB;
GRANT RESOURCE TO DATALAB;
ALTER USER DATALAB DEFAULT ROLE CONSOLE_DEVELOPER,DWROLE,GRAPH_DEVELOPER,OML_DEVELOPER;

-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'DATALAB',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'datalab',
        p_auto_rest_auth=> TRUE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => 'DATALAB',
            ENABLED => TRUE
    );
    commit;
END;
/

-- ENABLE GRAPH
ALTER USER DATALAB GRANT CONNECT THROUGH GRAPH$PROXY_USER;
-- ENABLE OML
ALTER USER DATALAB GRANT CONNECT THROUGH OML$PROXY;
-- QUOTA
ALTER USER DATALAB QUOTA UNLIMITED ON DATA;
