-- Creacion de tablas para almacenar la información de MOVII
CREATE TABLE MOVII_INFO (DOC_ID NUMBER, CHUNK_ID NUMBER, CHUNK_DATA CLOB)
CREATE TABLE TEST_NEWS (
    DOC_ID NUMBER,
    DOC_NAME VARCHAR2(255),
    CHUNK_ID NUMBER,
    CHUNK_DATA CLOB,
    EMBED VECTOR(1024)
)